CREATE TABLE promo_codes (
  id BIGINT NOT NULL AUTO_INCREMENT,
  code VARCHAR(40) NOT NULL,
  discount_type VARCHAR(20) NOT NULL,
  discount_value DECIMAL(10,2) NOT NULL,
  min_subtotal DECIMAL(10,2) NULL,
  max_uses INT NULL,
  used_count INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  valid_from TIMESTAMP NULL,
  valid_until TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_promo_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE orders
  ADD COLUMN promo_code VARCHAR(40) NULL AFTER shipping,
  ADD COLUMN discount DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER promo_code;

INSERT INTO promo_codes (code, discount_type, discount_value, min_subtotal, max_uses, active, valid_until)
VALUES
  ('WELCOME10', 'PERCENT', 10.00, 50.00, NULL, TRUE, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 YEAR)),
  ('SAVE15', 'FIXED', 15.00, 100.00, NULL, TRUE, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 YEAR)),
  ('ATELIER20', 'PERCENT', 20.00, 200.00, 500, TRUE, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 YEAR));
